version: "3.9"
services:

  db:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iris-net

  preprocessing:
    build: ./preprocessing
    container_name: preprocessing_container
    depends_on:
      - db
    volumes:
      - ./data:/data
    networks:
      - iris-net

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    command: mlflow ui --host 0.0.0.0 --port 5000
    networks:
      - iris-net

  # api:
  #   build: ./api
  #   container_name: api_container
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - mlflow
  #   networks:
  #     - iris-net

  api:
    build: .
    container_name: api_container
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mlflow
    networks:
      - iris-net
    volumes:
      - .:/app

  modeling:
    build:
      context: .
      dockerfile: Dockerfile.modeling
    container_name: modeling_container
    depends_on:
      - db
      - mlflow
    networks:
      - iris-net
    volumes:
      - .:/app


volumes:
  postgres_data:

networks:
  iris-net:
